# Programming Assignment 5
---
**Author:** Allie Baker  
**Version:** 1.0  
**Semester:** Spring 2024 

This *notebook* contains my solution(s) to **Programming Assignment 5**

### Problem 1 - Language Translator 

In [7]:
def create_translation_dictionary():
    translation_dict = {
        'apple': 'manzana',
        'banana': 'plátano',
        'car': 'coche',
        'dog': 'perro',
        'cat': 'gato',
        'house': 'casa',
        'tree': 'árbol',
        'book': 'libro',
        'computer': 'computadora',
        'sun': 'sol',
        'moon': 'luna',
        'water': 'agua',
        'food': 'comida',
        'hello': 'hola',
        'goodbye': 'adiós',
        'yes': 'sí',
        'no': 'no',
        'friend': 'amigo',
        'love': 'amor',
        'beautiful': 'hermoso'
    }
    return translation_dict

def translate_word(word, translation_dict):
    return translation_dict.get(word, "not found in dictionary")

def main():
    translation_dict = create_translation_dictionary()
    while True:
        word = input("Enter an English word to translate to Spanish (Q to quit): ").lower()
        if word == 'q':
            print("")
            break
        translation = translate_word(word, translation_dict)
        print("The Spanish translation is", translation)

if __name__ == "__main__":
    main()


Enter an English word to translate to Spanish (Q to quit):  apple


The Spanish translation is manzana


Enter an English word to translate to Spanish (Q to quit):  loves


The Spanish translation is not found in dictionary


Enter an English word to translate to Spanish (Q to quit):  Q


### Problem 2 - Translating Morse Code

In [10]:
def create_morse_code_dict():
    morse_code_dict = {
        'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....', 
        'I': '..', 'J': '.---', 'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 
        'Q': '--.-', 'R': '.-.', 'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-', 
        'Y': '-.--', 'Z': '--..',
        '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....', '6': '-....', 
        '7': '--...', '8': '---..', '9': '----.'
    }
    return morse_code_dict

def translate_to_morse_code(sentence, morse_code_dict):
    morse_code = ''
    for char in sentence:
        if char.upper() in morse_code_dict:
            morse_code += morse_code_dict[char.upper()] + ' '
        elif char == ' ':
            morse_code += '/ '
    return morse_code.strip()

def main():
    morse_code_dict = create_morse_code_dict()
    while True:
        sentence = input("Enter a sentence to translate to Morse code (q to quit): ").strip()
        if sentence.lower() == 'q':
            print("")
            break
        translation = translate_to_morse_code(sentence, morse_code_dict)
        print("Morse Code:", translation)

if __name__ == "__main__":
    main()


Enter a sentence to translate to Morse code (q to quit):  q


### Problem 3 - Comparing Minors/Majors

In [5]:
cs_minor = {"CS100", "CS101", "CS131", "CS215", "CS400", "CS233" or "CS330", "MATH120"}
bus_admin_minor = {"BUSA103", "BUSA203", "BUSA301", "BUSA305", "ACCT101", "ECON110", "FINA315", "MATH125" or "MATH117"}
bus_analytics_minor = {"BUSA103", "BUSA245", "BUSA346", "CS150", "DS160", "DS300"}
ds_major = {"BUSA103", "BUSA245", "BUSA346", "CS150", "DS160", "DS300", "DS450", "MATH205", "MATH215", "MATH430", "ECON410", "ECON322" "ECON351" or "DS444"}


overlap_bus_admin_and_analytics = bus_admin_minor.intersection(bus_analytics_minor)
print(f"i. Overlapping courses between Business Administration and Business Analytics minors: {overlap_bus_admin_and_analytics}")


all_courses_bus_admin_and_cs = bus_admin_minor.union(cs_minor)
print(f"ii. All courses for a minor in Business Administration and Computer Science: {all_courses_bus_admin_and_cs}")


bus_admin_not_in_analytics = bus_admin_minor.difference(bus_analytics_minor)
print(f"iii. Courses in the Business Administration minor but not in the Business Analytics minor: {bus_admin_not_in_analytics}")


overlap_cs_and_ds = cs_minor.intersection(ds_major)
print(f"iv. Overlapping courses between Computer Science and Data Science majors: {overlap_cs_and_ds if overlap_cs_and_ds else 'None'}")


is_bus_analytics_in_ds = bus_analytics_minor.issubset(ds_major)
print(f"v. Is the Business Analytics minor completely subsumed by the Data Science major? {'Yes' if is_bus_analytics_in_ds else 'No'}")


i. Overlapping courses between Business Administration and Business Analytics minors: {'BUSA103'}
ii. All courses for a minor in Business Administration and Computer Science: {'CS131', 'ACCT101', 'CS215', 'CS400', 'MATH125', 'CS101', 'FINA315', 'CS100', 'CS233', 'BUSA305', 'BUSA301', 'ECON110', 'MATH120', 'BUSA203', 'BUSA103'}
iii. Courses in the Business Administration minor but not in the Business Analytics minor: {'ACCT101', 'MATH125', 'FINA315', 'BUSA305', 'BUSA301', 'ECON110', 'BUSA203'}
iv. Overlapping courses between Computer Science and Data Science majors: None
v. Is the Business Analytics minor completely subsumed by the Data Science major? Yes


### Problem 4 - Working with Numpy 

In [6]:
import numpy as np

array1 = np.random.randint(0, 21, size=(5, 5))
array2 = np.random.randint(0, 21, size=(5, 5))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

matrix_product = np.matmul(array1, array2)
print("\nMatrix Product:")
print(matrix_product)

dot_product = np.dot(array1.flatten(), array2.flatten())
print("\nDot Product:")
print(dot_product)

determinant_array1 = np.linalg.det(array1)
inverse_array1 = np.linalg.inv(array1)
determinant_array2 = np.linalg.det(array2)
inverse_array2 = np.linalg.inv(array2)

print("\nDeterminant of Array 1:", determinant_array1)
print("Inverse of Array 1:")
print(inverse_array1)

print("\nDeterminant of Array 2:", determinant_array2)
print("Inverse of Array 2:")
print(inverse_array2)

array1d_1 = np.linspace(0, 1, 20)
array1d_2 = np.linspace(1, 2, 20)

concatenated_array = np.concatenate((array1d_1, array1d_2))

reshaped_array = concatenated_array.reshape((10, 4))

print("\nConcatenated Array:")
print(concatenated_array)
print("\nReshaped Array:")
print(reshaped_array)


Array 1:
[[16  2  6 17 11]
 [14 19 17 17 16]
 [ 0 16  0 18  0]
 [16  5 20  7 16]
 [12 13 11  2 20]]

Array 2:
[[ 0  6 18  3 16]
 [ 0  8 19  3  4]
 [ 7  6  0 13  7]
 [ 8 16 17  8 19]
 [ 9 12  4 15  0]]

Matrix Product:
[[277 552 659 433 629]
 [399 802 966 696 742]
 [144 416 610 192 406]
 [340 560 566 619 549]
 [273 514 577 534 359]]

Dot Product:
2513

Determinant of Array 1: -68172.00000000004
Inverse of Array 1:
[[ 0.14070293  1.14319662 -0.85144928 -0.8363551  -0.32285983]
 [ 0.01689843  0.5576483  -0.36956522 -0.40820278 -0.12885055]
 [-0.06501203 -0.14539694  0.12318841  0.19544681 -0.00428328]
 [-0.01502083 -0.49568738  0.38405797  0.36284692  0.11453383]
 [-0.05814704 -0.91885231  0.64492754  0.62336443  0.31837118]]

Determinant of Array 2: 10187.999999999973
Inverse of Array 2:
[[-2.45053004  2.16117     2.35904986  0.73949745 -2.38103651]
 [ 1.45318021 -1.38368669 -1.57096584 -0.35365135  1.53621908]
 [-0.74734982  0.74970554  0.76030624  0.19140165 -0.7614841 ]
 [ 0.50706714 